version: '3.1'
services:
  custom-nginx-proxy:
    image: nginx:1.10.1
    volumes:
      - ${STATIC_FILE_PATH}:/usr/share/nginx/html:ro
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d/default.conf:ro
      - ${NGINX_AUTH_PATH}:/opt/nginx/conf/conf.d/nginx.passwd:ro
    ports:
      - ${PROXY_PORT:-80}:80

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400