version: '3.1'
services:
  custom-nginx-proxy:
    image: nginx:1.10.1
    volumes:
      - ${PWD}/file_store:/usr/share/nginx/html:ro
      - ${PWD}/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${PROXY_PORT:-80}:80

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400